### Listar
GET http://localhost:3001

###
GET http://localhost:3001/melancia

### Cadastrar Produto
POST http://localhost:3001
Content-Type: application/json

{
    "nome" : "Melancia",
    "preco" : 10
}

